name: Publish

on:
  push:
    branches: 'main'

jobs:
  publish:
    name: "Publish Documentation (latest)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.6'
      - name: Install dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        run: |
          cd gh-pages
          julia --project=.. -e 'using Publish, epistlesofadifferenttime; deploy(epistlesofadifferenttime; root="/epistlesofadifferenttime", label="docs")'
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "(latest) Built by Publish.jl."
          git push
